#!/bin/bash
# WLpkg: Copyright 2019-2021 Valerio Messina efa@iol.it
# WLpkg is part of Wilderland - A Hobbit Environment
# Wilderland is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Wilderland is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Wilderland. If not, see <http://www.gnu.org/licenses/>.
# Special exception/limitation to GPL: not for commercial use

# Script to generate a Mingw package of 'Wilderland'
# used on: Mingw64=>bin64, Mingw32=>bin32

SRCPATH64="../SDL2_64" # path of DLLs needed to generate the Mingw64 package
SRCPATH32="../SDL2_32" # path of DLLs needed to generate the Mingw32 package
DSTPATH=".." # path where create the Mingw package directory

DEPS="libjpeg-8.dll libpng15-15.dll libtiff-5.dll libwebp-2.dll SDL.dll SDL_image.dll zlib1.dll"

echo "WLpkg: create a MinGW package of Wilderland"

# check for external dependency compliance
flag=0
for extCmd in 7z sed uname which ; do
   exist=`which $extCmd 2> /dev/null`
   if (test "" = "$exist") then
      echo "Required external dependency: "\"$extCmd\"" unsatisfied!"
      flag=1
   fi
done
if (test "$flag" = 1) then
   echo "ERROR: Install the required packages and retry. Exit"
   exit
fi

CPU=`uname -m` # i686 or x86_64
OS=`uname -o`
VER=`ls WL???package.txt | sed 's/package.txt//'`
if (! test "$OS" = "Msys") then
   echo "ERROR: work on MinGW only"
   exit
fi
BIT=64
if (test "$MSYSTEM" = "MINGW32") then
   BIT=32
fi

echo "CPU: $CPU"
echo "OS : $OS"
echo "VER: $VER"
echo "BIT: $BIT"
if (test "$BIT" = "64") then
   echo "SRC: $SRCPATH64"
fi
if (test "$BIT" = "32") then
   echo "SRC: $SRCPATH32"
fi
echo "DST: $DSTPATH"
echo "Creating Wilderland $VER package for MinGW$BIT ..."
mkdir -p $DSTPATH/"$VER"_Win$BIT
mkdir -p $DSTPATH/"$VER"_Win$BIT/TapCon
mkdir -p $DSTPATH/"$VER"_Win$BIT/Z80
cp *c *.h $DSTPATH/"$VER"_Win$BIT
cp TapCon/TapCon.c $DSTPATH/"$VER"_Win$BIT/TapCon
cp Z80/* $DSTPATH/"$VER"_Win$BIT/Z80
cp Makefile* $DSTPATH/"$VER"_Win$BIT
cp *.txt $DSTPATH/"$VER"_Win$BIT
cp CharSetSpectrum8x8.bin GameMap.png HOBBIT.SCR $DSTPATH/"$VER"_Win$BIT
cp WLpkg $DSTPATH/"$VER"_Win$BIT
if (test "$BIT" = "64") then
   cp WL.exe $DSTPATH/"$VER"_Win$BIT
   cp TapCon/TapCon.exe $DSTPATH/"$VER"_Win$BIT/TapCon
   for DLL in $DEPS ; do
      cp $SRCPATH64/$DLL $DSTPATH/"$VER"_Win$BIT
   done
fi
if (test "$BIT" = "32") then
   cp WL32.exe $DSTPATH/"$VER"_Win$BIT
   cp TapCon/TapCon32.exe $DSTPATH/"$VER"_Win$BIT/TapCon
   for DLL in $DEPS ; do
      cp $SRCPATH32/$DLL $DSTPATH/"$VER"_Win$BIT
   done
fi
echo ""
echo -n "Compressing with 7zip ..."
cd $DSTPATH
if (test -f "$VER"_Win$BIT.7z) then
   rm "$VER"_Win$BIT.7z
fi
7z a -m0=lzma -mx=9 -r "$VER"_Win$BIT.7z "$VER"_Win$BIT
echo Done
